services:
  - type: web
    name: lynoralink-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /v1/health
    preDeployCommand: npx prisma migrate deploy --schema prisma/schema.prisma
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: APP_URL
        sync: false
      - key: EMAIL_PROVIDER
        value: brevo
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: BREVO_FROM_NAME
        value: LynoraLink
      - key: WEB_PUSH_VAPID_PUBLIC_KEY
        value: BI_dbBnOg1YYh73_ovsfVLAhYAGYpHExFhH0IPAiz-gIhPhf33nFDh00NcW9Seotam9vJEaRDv8iFzi4eRahb-o
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
