import crypto from "node:crypto";
import { getSessionUserId } from "./auth.js";
import { prisma } from "./db.js";

function parse(value) { try { return JSON.parse(value || "null") || {}; } catch { return {}; } }
function shape(page, user) { const name = page.name || "Mon entreprise"; const isPremium = Boolean(user.subscription && ["ACTIVE", "TRIALING"].includes(user.subscription.status) && !(user.subscription.currentPeriodEnd && user.subscription.currentPeriodEnd <= new Date())); return { ...page, id: user.id, name, displayName: name, logoUrl: page.logoUrl || null, avatarUrl: page.logoUrl || null, bannerUrl: page.bannerUrl || null, coverUrl: page.bannerUrl || null, isPremium, isPlatformAdmin: user.role === "admin", media: Array.isArray(page.media) ? page.media : [], jobs: Array.isArray(page.jobs) ? page.jobs : [], stats: { posts: 0, comments: 0, followers: 0 } }; }
async function current(userId) { const user = await prisma.user.findUnique({ where: { id: userId }, select: { id: true, createdAt: true, role: true, subscription: { select: { status: true, currentPeriodEnd: true } } } }); const setting = await prisma.userSetting.findUnique({ where: { userId_key: { userId, key: "companyPage" } } }); return user && setting ? { user, setting, page: parse(setting.value) } : null; }

export async function registerCompanyRoutes(app) {
  app.get("/v1/company", async (request, reply) => { const userId = await getSessionUserId(request); if (!userId) return reply.code(401).send({ error: "Non authentifié" }); const item = await current(userId); return reply.send(item ? shape(item.page, item.user) : null); });
  app.put("/v1/company", async (request, reply) => { const userId = await getSessionUserId(request); if (!userId) return reply.code(401).send({ error: "Non authentifié" }); const item = await current(userId); const body = request.body || {}; const page = { ...(item?.page || {}), name: String(body.displayName ?? body.name ?? item?.page?.name ?? "").trim() || "Mon entreprise", slogan: body.slogan ?? item?.page?.slogan ?? null, description: body.description ?? item?.page?.description ?? null, industry: body.industry ?? item?.page?.industry ?? null, location: body.location ?? item?.page?.location ?? null, website: body.website ?? item?.page?.website ?? null, logoUrl: body.logoUrl ?? item?.page?.logoUrl ?? null, bannerUrl: body.bannerUrl ?? item?.page?.bannerUrl ?? null, media: Array.isArray(body.media) ? body.media : item?.page?.media || [], jobs: Array.isArray(body.jobs) ? body.jobs.slice(0, 100).map((job) => ({ ...job, id: String(job.id || crypto.randomUUID()), title: String(job.title || "").trim().slice(0, 140), description: String(job.description || "").trim().slice(0, 3000) })).filter((job) => job.title && job.description) : item?.page?.jobs || [], createdAt: item?.page?.createdAt || new Date().toISOString() }; await prisma.userSetting.upsert({ where: { userId_key: { userId, key: "companyPage" } }, update: { value: JSON.stringify(page) }, create: { userId, key: "companyPage", value: JSON.stringify(page) } }); const user = await prisma.user.findUnique({ where: { id: userId }, select: { id: true, createdAt: true } }); return reply.send(shape(page, user)); });
  app.delete("/v1/company", async (request, reply) => { const userId = await getSessionUserId(request); if (!userId) return reply.code(401).send({ error: "Non authentifié" }); const item = await current(userId); if (!item) return reply.code(404).send({ error: "Page entreprise introuvable" }); if (request.body?.confirmation !== item.page.name) return reply.code(400).send({ error: `Saisissez exactement « ${item.page.name} » pour confirmer.` }); await prisma.$transaction([prisma.post.updateMany({ where: { companyPageId: userId }, data: { companyPageId: null } }), prisma.userSetting.delete({ where: { id: item.setting.id } })]); return reply.send({ deleted: true }); });
}
